name: News Intelligence (Refactored)

on:
  workflow_dispatch:
    inputs:
      callsigns:
        description: "Optional: comma-separated callsigns to limit run"
        required: false
        type: string
      dry_run:
        description: "Dry run mode (no actual changes)"
        required: false
        default: "false"
        type: choice
        options: ["true","false"]
      lookback_days:
        description: "Intel lookback window (days)"
        required: false
        default: "10"
        type: string
      max_per_org:
        description: "Max items per org"
        required: false
        default: "5"
        type: string
  schedule:
    - cron: "15 13 * * FRI"  # Run 15 minutes after main workflow
  workflow_run:
    workflows: ["Weekly Digest"]
    types: [completed]

permissions:
  contents: read

jobs:
  news:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run news intelligence workflow
        env:
          # Gmail API
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}

          # Notion API
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_COMPANIES_DB_ID: ${{ secrets.NOTION_COMPANIES_DB_ID }}
          NOTION_INTEL_DB_ID: ${{ secrets.NOTION_INTEL_DB_ID }}

          # OpenAI API
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_CHAT_MODEL: ${{ vars.OPENAI_CHAT_MODEL || 'gpt-4o-mini' }}
          OPENAI_TEMPERATURE: ${{ vars.OPENAI_TEMPERATURE || '0.2' }}

          # Google Search
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}

          # Configuration
          ENVIRONMENT: 'production'
          DEBUG: 'false'
          DRY_RUN: ${{ inputs.dry_run }}
          FILTER_CALLSIGNS: ${{ inputs.callsigns }}
          INTEL_LOOKBACK_DAYS: ${{ inputs.lookback_days }}
          INTEL_MAX_PER_ORG: ${{ inputs.max_per_org }}

        run: |
          # Run the news intelligence analysis
          python -m app.main news \
            ${{ inputs.callsigns && format('--callsigns="{0}"', inputs.callsigns) || '' }} \
            --lookback-days='${{ inputs.lookback_days }}' \
            ${{ inputs.dry_run == 'true' && '--no-email' || '' }}
