name: Test Workflow

on:
  workflow_dispatch: {}       # enables manual testing
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run test suite
        run: |
          pytest tests/ -v --tb=short

      - name: Test digest workflow (dry-run)
        env:
          GMAIL_CLIENT_ID: "test_client_id"
          GMAIL_CLIENT_SECRET: "test_client_secret"
          GMAIL_REFRESH_TOKEN: "test_refresh_token"
          GMAIL_USER: "test@example.com"
          NOTION_API_KEY: "test_notion_key"
          ENVIRONMENT: 'test'
          DEBUG: 'true'
          DRY_RUN: 'true'
        run: |
          python -m app.main --dry-run digest-dry-run --max-messages 1

      - name: Test CSV parsing
        env:
          ENVIRONMENT: 'test'
          DEBUG: 'true'
        run: |
          if [ -f "files/Will Accounts Demographics_2025-09-01T09_09_22.742205229Z.csv" ]; then
            python -m app.main test-csv "files/Will Accounts Demographics_2025-09-01T09_09_22.742205229Z.csv"
          else
            echo "CSV file not found, skipping CSV test"
          fi